"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Otto.py']
#DATA_FILES = ['Otto.xib']
DATA_FILES = ['Otto.nib']
INCLUDES = ['json', 'chardet', 'mutagen', 'pymongo', 'bson', 'StringIO', 'PIL', 'PIL.Image']
#OPTIONS = {'argv_emulation': True}
#OPTIONS = { 'iconfile': '../static/images/ottoicon.icns', 'packages': '../lib/python2.7' }
OPTIONS = { 'iconfile': '../static/images/ottoicon.icns', 'includes': INCLUDES }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
